import type { Language } from "../types";

export const SETTINGS_TRANSLATIONS: Partial<Record<Language, Record<string, string>>> = {
  fr: {
    "语言包管理": "Packs de langue", "管理语言包": "Gérer les langues", "退出后是否保持页面": "Conserver la page après fermeture", "不保持": "Ne pas conserver", "保持当前筛选": "Conserver les filtres actuels", "保持当月界面": "Conserver la vue du mois actuel",
    "删除后将从语言选项中隐藏，可随时恢复。简体中文为内置基础语言。": "Une langue supprimée est masquée dans la liste et peut être restaurée à tout moment. Le chinois simplifié est intégré.", "删除的语言包会从语言列表隐藏，之后仍可在这里恢复。": "Les langues supprimées sont masquées et peuvent être restaurées ici.", "内置基础语言": "Langue de base intégrée", "已安装": "Installé", "已删除": "Supprimé", "内置": "Intégré", "恢复": "Restaurer", "管理": "Gérer",
    "返回顶部按钮": "Bouton de retour en haut", "收入颜色": "Couleur des revenus", "支出颜色": "Couleur des dépenses",
    "打开赞助面板": "Ouvrir le soutien", "打开反馈面板": "Ouvrir les commentaires", "录入方式": "Mode de saisie", "记账方式": "Interface de saisie", "桌面版为全程键盘记账；手机版为完整表单记账。": "La version ordinateur fonctionne entièrement au clavier ; la version mobile utilise un formulaire complet.", "手机版连续记账": "Saisie continue sur mobile", "手机版保存后打开仪表盘": "Ouvrir le tableau de bord après la saisie mobile", "允许内容重复": "Autoriser les libellés en double", "关闭后，新建或修改账目时不允许与同日账目使用相同内容。": "Si désactivé, les opérations du même jour ne peuvent pas avoir le même libellé.",
    "录入字段与顺序": "Champs de saisie et ordre", "录入预设": "Préréglages de saisie", "明细行为": "Comportement du tableau", "恢复默认列宽": "Rétablir les largeurs par défaut", "启用行内编辑": "Activer la modification en ligne", "删除前二次确认": "Confirmer avant suppression", "撤销删除时间": "Délai d’annulation", "可设置为0-15秒，只能设置为整数。": "Saisissez un entier de 0 à 15 secondes.", "显示编辑按钮": "Afficher le bouton Modifier", "显示打开Markdown按钮": "Afficher le bouton Markdown", "显示删除按钮": "Afficher le bouton Supprimer", "表头顺序": "Ordre des colonnes", "拖动左侧滑块调整顺序；右侧眼睛控制是否显示，铅笔控制能否行内编辑。": "Faites glisser la poignée gauche pour réorganiser ; l’œil gère l’affichage et le crayon la modification en ligne.",
    "金额格式": "Format des montants", "货币符号": "Symbole monétaire", "仅修改符号，不转换金额。": "Modifie uniquement le symbole, sans convertir les montants.", "金额分位方式": "Regroupement des chiffres", "中文万位分组（1,0000）": "Groupement chinois par 4 chiffres (1,0000)", "国际千位分组（10,000）": "Groupement international par 3 chiffres (10,000)", "不使用分隔符（10000）": "Sans séparateur (10000)", "日期、时间与星期": "Date, heure et semaine", "年月格式": "Format année-mois", "用于仪表盘的月份选择。": "Utilisé pour choisir le mois du tableau de bord.", "账目日期格式": "Format de date des opérations", "用于账目明细、汇总和图表提示。": "Utilisé dans le tableau, les résumés et les infobulles.", "时间格式": "Format de l’heure", "24小时制（18:30）": "24 heures (18:30)", "12小时制（06:30 PM）": "12 heures (06:30 PM)", "每周起始日": "Premier jour de la semaine",
    "存储目录": "Dossiers de stockage", "账目存储目录": "Dossier des opérations", "CSV导出目录": "Dossier d’export CSV", "附件存储目录": "Dossier des pièces jointes", "Markdown算式存储": "Stockage des formules Markdown", "把算式写入备注": "Écrire les formules dans les notes", "桌面版记账快捷键": "Raccourcis de saisie sur ordinateur", "全局快捷键": "Raccourcis globaux", "启用全局快捷键": "Activer les raccourcis globaux", "确认 / 下一步": "Confirmer / Suivant", "上一个选项": "Option précédente", "下一个选项": "Option suivante", "还原默认": "Rétablir les valeurs par défaut", "作者GitHub主页": "GitHub de l’auteur", "作者B站主页": "Page Bilibili de l’auteur", "打开GitHub": "Ouvrir GitHub", "打开B站": "Ouvrir Bilibili", "打开GitHub Issues": "Ouvrir GitHub Issues"
  },
  ru: {
    "语言包管理": "Языковые пакеты", "管理语言包": "Управление языками", "退出后是否保持页面": "Сохранять страницу после закрытия", "不保持": "Не сохранять", "保持当前筛选": "Сохранять текущие фильтры", "保持当月界面": "Сохранять вид текущего месяца",
    "删除后将从语言选项中隐藏，可随时恢复。简体中文为内置基础语言。": "Удалённый язык скрывается из списка и может быть восстановлен. Упрощённый китайский встроен.", "删除的语言包会从语言列表隐藏，之后仍可在这里恢复。": "Удалённые языки скрываются из списка и могут быть восстановлены здесь.", "内置基础语言": "Встроенный основной язык", "已安装": "Установлен", "已删除": "Удалён", "内置": "Встроен", "恢复": "Восстановить", "管理": "Управлять",
    "返回顶部按钮": "Кнопка возврата наверх", "收入颜色": "Цвет дохода", "支出颜色": "Цвет расхода",
    "打开赞助面板": "Открыть поддержку", "打开反馈面板": "Открыть обратную связь", "录入方式": "Режим ввода", "记账方式": "Интерфейс ввода", "桌面版为全程键盘记账；手机版为完整表单记账。": "На компьютере доступен полностью клавиатурный ввод, на телефоне — полная форма.", "手机版连续记账": "Непрерывный ввод на телефоне", "手机版保存后打开仪表盘": "Открывать панель после мобильного ввода", "允许内容重复": "Разрешить одинаковые описания", "关闭后，新建或修改账目时不允许与同日账目使用相同内容。": "Если выключено, операции одного дня не могут иметь одинаковое описание.",
    "录入字段与顺序": "Поля ввода и порядок", "录入预设": "Предустановки ввода", "明细行为": "Поведение таблицы", "恢复默认列宽": "Восстановить ширину столбцов", "启用行内编辑": "Включить редактирование в строке", "删除前二次确认": "Подтверждать удаление", "撤销删除时间": "Время отмены удаления", "可设置为0-15秒，只能设置为整数。": "Введите целое число от 0 до 15 секунд.", "显示编辑按钮": "Показывать кнопку редактирования", "显示打开Markdown按钮": "Показывать кнопку Markdown", "显示删除按钮": "Показывать кнопку удаления", "表头顺序": "Порядок столбцов", "拖动左侧滑块调整顺序；右侧眼睛控制是否显示，铅笔控制能否行内编辑。": "Перетаскивайте левый маркер; значок глаза управляет видимостью, карандаш — редактированием.",
    "金额格式": "Формат суммы", "货币符号": "Символ валюты", "仅修改符号，不转换金额。": "Меняется только символ, без пересчёта сумм.", "金额分位方式": "Группировка цифр", "中文万位分组（1,0000）": "Китайская группировка по 4 цифры (1,0000)", "国际千位分组（10,000）": "Международная группировка по 3 цифры (10,000)", "不使用分隔符（10000）": "Без разделителя (10000)", "日期、时间与星期": "Дата, время и неделя", "年月格式": "Формат года и месяца", "用于仪表盘的月份选择。": "Используется в выборе месяца на панели.", "账目日期格式": "Формат даты операции", "用于账目明细、汇总和图表提示。": "Используется в таблице, итогах и подсказках графиков.", "时间格式": "Формат времени", "24小时制（18:30）": "24 часа (18:30)", "12小时制（06:30 PM）": "12 часов (06:30 PM)", "每周起始日": "Первый день недели",
    "存储目录": "Папки хранения", "账目存储目录": "Папка операций", "CSV导出目录": "Папка экспорта CSV", "附件存储目录": "Папка вложений", "Markdown算式存储": "Хранение формул Markdown", "把算式写入备注": "Записывать формулы в примечания", "桌面版记账快捷键": "Клавиши ввода на компьютере", "全局快捷键": "Глобальные горячие клавиши", "启用全局快捷键": "Включить глобальные клавиши", "确认 / 下一步": "Подтвердить / Далее", "上一个选项": "Предыдущий вариант", "下一个选项": "Следующий вариант", "还原默认": "Восстановить стандартные", "作者GitHub主页": "GitHub автора", "作者B站主页": "Страница автора на Bilibili", "打开GitHub": "Открыть GitHub", "打开B站": "Открыть Bilibili", "打开GitHub Issues": "Открыть GitHub Issues"
  },
  es: {
    "语言包管理": "Paquetes de idioma", "管理语言包": "Gestionar idiomas", "退出后是否保持页面": "Conservar la página al cerrar", "不保持": "No conservar", "保持当前筛选": "Conservar filtros actuales", "保持当月界面": "Conservar vista del mes actual",
    "删除后将从语言选项中隐藏，可随时恢复。简体中文为内置基础语言。": "Un idioma eliminado se oculta de la lista y puede restaurarse. El chino simplificado está integrado.", "删除的语言包会从语言列表隐藏，之后仍可在这里恢复。": "Los idiomas eliminados se ocultan y pueden restaurarse aquí.", "内置基础语言": "Idioma base integrado", "已安装": "Instalado", "已删除": "Eliminado", "内置": "Integrado", "恢复": "Restaurar", "管理": "Gestionar",
    "返回顶部按钮": "Botón para volver arriba", "收入颜色": "Color de ingresos", "支出颜色": "Color de gastos",
    "打开赞助面板": "Abrir panel de apoyo", "打开反馈面板": "Abrir comentarios", "录入方式": "Modo de registro", "记账方式": "Interfaz de registro", "桌面版为全程键盘记账；手机版为完整表单记账。": "El escritorio permite registrar solo con teclado; el móvil usa un formulario completo.", "手机版连续记账": "Registro continuo en móvil", "手机版保存后打开仪表盘": "Abrir el panel tras guardar en móvil", "允许内容重复": "Permitir descripciones duplicadas", "关闭后，新建或修改账目时不允许与同日账目使用相同内容。": "Si se desactiva, las operaciones del mismo día no pueden compartir descripción.",
    "录入字段与顺序": "Campos de registro y orden", "录入预设": "Preajustes de registro", "明细行为": "Comportamiento de la tabla", "恢复默认列宽": "Restaurar anchos predeterminados", "启用行内编辑": "Activar edición en línea", "删除前二次确认": "Confirmar antes de eliminar", "撤销删除时间": "Tiempo para deshacer", "可设置为0-15秒，只能设置为整数。": "Introduce un entero entre 0 y 15 segundos.", "显示编辑按钮": "Mostrar botón Editar", "显示打开Markdown按钮": "Mostrar botón Markdown", "显示删除按钮": "Mostrar botón Eliminar", "表头顺序": "Orden de columnas", "拖动左侧滑块调整顺序；右侧眼睛控制是否显示，铅笔控制能否行内编辑。": "Arrastra el asa izquierda; el ojo controla la visibilidad y el lápiz la edición en línea.",
    "金额格式": "Formato de importes", "货币符号": "Símbolo de moneda", "仅修改符号，不转换金额。": "Solo cambia el símbolo; no convierte importes.", "金额分位方式": "Agrupación de dígitos", "中文万位分组（1,0000）": "Agrupación china de 4 dígitos (1,0000)", "国际千位分组（10,000）": "Agrupación internacional de 3 dígitos (10,000)", "不使用分隔符（10000）": "Sin separador (10000)", "日期、时间与星期": "Fecha, hora y semana", "年月格式": "Formato año-mes", "用于仪表盘的月份选择。": "Se usa en el selector de mes del panel.", "账目日期格式": "Formato de fecha de operaciones", "用于账目明细、汇总和图表提示。": "Se usa en la tabla, los resúmenes y las ayudas de gráficos.", "时间格式": "Formato de hora", "24小时制（18:30）": "24 horas (18:30)", "12小时制（06:30 PM）": "12 horas (06:30 PM)", "每周起始日": "Primer día de la semana",
    "存储目录": "Carpetas de almacenamiento", "账目存储目录": "Carpeta de operaciones", "CSV导出目录": "Carpeta de exportación CSV", "附件存储目录": "Carpeta de adjuntos", "Markdown算式存储": "Almacenamiento de fórmulas Markdown", "把算式写入备注": "Guardar fórmulas en las notas", "桌面版记账快捷键": "Atajos de registro en escritorio", "全局快捷键": "Atajos globales", "启用全局快捷键": "Activar atajos globales", "确认 / 下一步": "Confirmar / Siguiente", "上一个选项": "Opción anterior", "下一个选项": "Opción siguiente", "还原默认": "Restaurar valores predeterminados", "作者GitHub主页": "GitHub del autor", "作者B站主页": "Página Bilibili del autor", "打开GitHub": "Abrir GitHub", "打开B站": "Abrir Bilibili", "打开GitHub Issues": "Abrir GitHub Issues"
  },
  ar: {
    "语言包管理": "حزم اللغات", "管理语言包": "إدارة اللغات", "退出后是否保持页面": "الاحتفاظ بالصفحة بعد الإغلاق", "不保持": "عدم الاحتفاظ", "保持当前筛选": "الاحتفاظ بعوامل التصفية الحالية", "保持当月界面": "الاحتفاظ بعرض الشهر الحالي",
    "删除后将从语言选项中隐藏，可随时恢复。简体中文为内置基础语言。": "تُخفى اللغة المحذوفة من القائمة ويمكن استعادتها في أي وقت. الصينية المبسطة مدمجة.", "删除的语言包会从语言列表隐藏，之后仍可在这里恢复。": "تُخفى اللغات المحذوفة ويمكن استعادتها هنا.", "内置基础语言": "لغة أساسية مدمجة", "已安装": "مثبتة", "已删除": "محذوفة", "内置": "مدمجة", "恢复": "استعادة", "管理": "إدارة",
    "返回顶部按钮": "زر العودة للأعلى", "收入颜色": "لون الدخل", "支出颜色": "لون المصروف",
    "打开赞助面板": "فتح لوحة الدعم", "打开反馈面板": "فتح الملاحظات", "录入方式": "وضع الإدخال", "记账方式": "واجهة الإدخال", "桌面版为全程键盘记账；手机版为完整表单记账。": "يوفر سطح المكتب إدخالاً كاملاً بلوحة المفاتيح، ويستخدم الهاتف نموذجاً كاملاً.", "手机版连续记账": "إدخال متتابع على الهاتف", "手机版保存后打开仪表盘": "فتح اللوحة بعد الحفظ على الهاتف", "允许内容重复": "السماح بالأوصاف المكررة", "关闭后，新建或修改账目时不允许与同日账目使用相同内容。": "عند التعطيل لا يمكن لمعاملات اليوم نفسه استخدام الوصف ذاته.",
    "录入字段与顺序": "حقول الإدخال وترتيبها", "录入预设": "إعدادات الإدخال المسبقة", "明细行为": "سلوك الجدول", "恢复默认列宽": "استعادة عرض الأعمدة", "启用行内编辑": "تمكين التحرير داخل الصف", "删除前二次确认": "التأكيد قبل الحذف", "撤销删除时间": "مدة التراجع عن الحذف", "可设置为0-15秒，只能设置为整数。": "أدخل عدداً صحيحاً من 0 إلى 15 ثانية.", "显示编辑按钮": "إظهار زر التعديل", "显示打开Markdown按钮": "إظهار زر Markdown", "显示删除按钮": "إظهار زر الحذف", "表头顺序": "ترتيب الأعمدة", "拖动左侧滑块调整顺序；右侧眼睛控制是否显示，铅笔控制能否行内编辑。": "اسحب المقبض؛ تتحكم العين في الظهور والقلم في التحرير داخل الصف.",
    "金额格式": "تنسيق المبلغ", "货币符号": "رمز العملة", "仅修改符号，不转换金额。": "يغيّر الرمز فقط ولا يحوّل المبالغ.", "金额分位方式": "تجميع الأرقام", "中文万位分组（1,0000）": "تجميع صيني كل 4 أرقام (1,0000)", "国际千位分组（10,000）": "تجميع دولي كل 3 أرقام (10,000)", "不使用分隔符（10000）": "من دون فاصل (10000)", "日期、时间与星期": "التاريخ والوقت والأسبوع", "年月格式": "تنسيق السنة والشهر", "用于仪表盘的月份选择。": "يُستخدم لاختيار شهر لوحة المعلومات.", "账目日期格式": "تنسيق تاريخ المعاملة", "用于账目明细、汇总和图表提示。": "يُستخدم في الجدول والملخصات وتلميحات الرسوم.", "时间格式": "تنسيق الوقت", "24小时制（18:30）": "24 ساعة (18:30)", "12小时制（06:30 PM）": "12 ساعة (06:30 PM)", "每周起始日": "أول يوم في الأسبوع",
    "存储目录": "مجلدات التخزين", "账目存储目录": "مجلد المعاملات", "CSV导出目录": "مجلد تصدير CSV", "附件存储目录": "مجلد المرفقات", "Markdown算式存储": "تخزين صيغ Markdown", "把算式写入备注": "كتابة الصيغ في الملاحظات", "桌面版记账快捷键": "اختصارات إدخال سطح المكتب", "全局快捷键": "اختصارات عامة", "启用全局快捷键": "تمكين الاختصارات العامة", "确认 / 下一步": "تأكيد / التالي", "上一个选项": "الخيار السابق", "下一个选项": "الخيار التالي", "还原默认": "استعادة الافتراضي", "作者GitHub主页": "GitHub للمؤلف", "作者B站主页": "صفحة المؤلف على Bilibili", "打开GitHub": "فتح GitHub", "打开B站": "فتح Bilibili", "打开GitHub Issues": "فتح GitHub Issues"
  },
  ja: {
    "语言包管理": "言語パック", "管理语言包": "言語を管理", "退出后是否保持页面": "終了後も画面を保持", "不保持": "保持しない", "保持当前筛选": "現在のフィルターを保持", "保持当月界面": "現在の月画面を保持",
    "删除后将从语言选项中隐藏，可随时恢复。简体中文为内置基础语言。": "削除した言語は一覧から非表示になり、いつでも復元できます。簡体字中国語は内蔵されています。", "删除的语言包会从语言列表隐藏，之后仍可在这里恢复。": "削除した言語は一覧から非表示になり、ここで復元できます。", "内置基础语言": "内蔵の基本言語", "已安装": "インストール済み", "已删除": "削除済み", "内置": "内蔵", "恢复": "復元", "管理": "管理",
    "返回顶部按钮": "トップへ戻るボタン", "收入颜色": "収入の色", "支出颜色": "支出の色",
    "打开赞助面板": "支援画面を開く", "打开反馈面板": "フィードバックを開く", "录入方式": "入力方法", "记账方式": "入力画面", "桌面版为全程键盘记账；手机版为完整表单记账。": "デスクトップ版はキーボードだけで入力でき、モバイル版は完全なフォームを使用します。", "手机版连续记账": "モバイル連続入力", "手机版保存后打开仪表盘": "モバイル保存後にダッシュボードを開く", "允许内容重复": "同じ内容を許可", "关闭后，新建或修改账目时不允许与同日账目使用相同内容。": "無効にすると、同じ日の取引に同一内容を使用できません。",
    "录入字段与顺序": "入力項目と順序", "录入预设": "入力プリセット", "明细行为": "明細表の動作", "恢复默认列宽": "既定の列幅に戻す", "启用行内编辑": "行内編集を有効化", "删除前二次确认": "削除前に確認", "撤销删除时间": "削除を元に戻せる時間", "可设置为0-15秒，只能设置为整数。": "0～15秒の整数を入力してください。", "显示编辑按钮": "編集ボタンを表示", "显示打开Markdown按钮": "Markdownボタンを表示", "显示删除按钮": "削除ボタンを表示", "表头顺序": "列の順序", "拖动左侧滑块调整顺序；右侧眼睛控制是否显示，铅笔控制能否行内编辑。": "左のハンドルで並べ替え、目で表示、鉛筆で行内編集を切り替えます。",
    "金额格式": "金額の形式", "货币符号": "通貨記号", "仅修改符号，不转换金额。": "記号だけを変更し、金額は換算しません。", "金额分位方式": "桁区切り", "中文万位分组（1,0000）": "中国式4桁区切り (1,0000)", "国际千位分组（10,000）": "国際式3桁区切り (10,000)", "不使用分隔符（10000）": "区切りなし (10000)", "日期、时间与星期": "日付・時刻・週", "年月格式": "年月の形式", "用于仪表盘的月份选择。": "ダッシュボードの月選択に使用します。", "账目日期格式": "取引日付の形式", "用于账目明细、汇总和图表提示。": "明細、集計、グラフのヒントに使用します。", "时间格式": "時刻形式", "24小时制（18:30）": "24時間制 (18:30)", "12小时制（06:30 PM）": "12時間制 (06:30 PM)", "每周起始日": "週の開始曜日",
    "存储目录": "保存フォルダー", "账目存储目录": "取引フォルダー", "CSV导出目录": "CSV出力フォルダー", "附件存储目录": "添付ファイルフォルダー", "Markdown算式存储": "Markdown数式の保存", "把算式写入备注": "数式をメモに書き込む", "桌面版记账快捷键": "デスクトップ入力ショートカット", "全局快捷键": "グローバルショートカット", "启用全局快捷键": "グローバルショートカットを有効化", "确认 / 下一步": "確定 / 次へ", "上一个选项": "前の項目", "下一个选项": "次の項目", "还原默认": "既定値に戻す", "作者GitHub主页": "作者のGitHub", "作者B站主页": "作者のBilibili", "打开GitHub": "GitHubを開く", "打开B站": "Bilibiliを開く", "打开GitHub Issues": "GitHub Issuesを開く"
  },
  ko: {
    "语言包管理": "언어 팩", "管理语言包": "언어 관리", "退出后是否保持页面": "종료 후 화면 유지", "不保持": "유지 안 함", "保持当前筛选": "현재 필터 유지", "保持当月界面": "현재 월 화면 유지",
    "删除后将从语言选项中隐藏，可随时恢复。简体中文为内置基础语言。": "삭제한 언어는 목록에서 숨겨지며 언제든 복원할 수 있습니다. 중국어 간체는 기본 내장 언어입니다.", "删除的语言包会从语言列表隐藏，之后仍可在这里恢复。": "삭제한 언어는 목록에서 숨겨지며 여기에서 복원할 수 있습니다.", "内置基础语言": "내장 기본 언어", "已安装": "설치됨", "已删除": "삭제됨", "内置": "내장", "恢复": "복원", "管理": "관리",
    "返回顶部按钮": "맨 위로 버튼", "收入颜色": "수입 색상", "支出颜色": "지출 색상",
    "打开赞助面板": "후원 패널 열기", "打开反馈面板": "피드백 열기", "录入方式": "입력 방식", "记账方式": "입력 화면", "桌面版为全程键盘记账；手机版为完整表单记账。": "데스크톱은 키보드만으로 입력하고 모바일은 전체 양식을 사용합니다.", "手机版连续记账": "모바일 연속 입력", "手机版保存后打开仪表盘": "모바일 저장 후 대시보드 열기", "允许内容重复": "중복 설명 허용", "关闭后，新建或修改账目时不允许与同日账目使用相同内容。": "끄면 같은 날짜의 거래에 동일한 설명을 사용할 수 없습니다.",
    "录入字段与顺序": "입력 필드 및 순서", "录入预设": "입력 사전 설정", "明细行为": "표 동작", "恢复默认列宽": "기본 열 너비 복원", "启用行内编辑": "행 편집 사용", "删除前二次确认": "삭제 전 확인", "撤销删除时间": "삭제 취소 시간", "可设置为0-15秒，只能设置为整数。": "0~15초의 정수를 입력하세요.", "显示编辑按钮": "편집 버튼 표시", "显示打开Markdown按钮": "Markdown 버튼 표시", "显示删除按钮": "삭제 버튼 표시", "表头顺序": "열 순서", "拖动左侧滑块调整顺序；右侧眼睛控制是否显示，铅笔控制能否行内编辑。": "왼쪽 핸들로 순서를 바꾸고 눈은 표시, 연필은 행 편집을 제어합니다.",
    "金额格式": "금액 형식", "货币符号": "통화 기호", "仅修改符号，不转换金额。": "기호만 변경하며 금액은 환산하지 않습니다.", "金额分位方式": "숫자 묶음", "中文万位分组（1,0000）": "중국식 4자리 묶음 (1,0000)", "国际千位分组（10,000）": "국제식 3자리 묶음 (10,000)", "不使用分隔符（10000）": "구분 기호 없음 (10000)", "日期、时间与星期": "날짜, 시간 및 주", "年月格式": "연월 형식", "用于仪表盘的月份选择。": "대시보드 월 선택에 사용합니다.", "账目日期格式": "거래 날짜 형식", "用于账目明细、汇总和图表提示。": "표, 요약 및 차트 도움말에 사용합니다.", "时间格式": "시간 형식", "24小时制（18:30）": "24시간제 (18:30)", "12小时制（06:30 PM）": "12시간제 (06:30 PM)", "每周起始日": "한 주의 시작 요일",
    "存储目录": "저장 폴더", "账目存储目录": "거래 폴더", "CSV导出目录": "CSV 내보내기 폴더", "附件存储目录": "첨부 파일 폴더", "Markdown算式存储": "Markdown 수식 저장", "把算式写入备注": "수식을 메모에 기록", "桌面版记账快捷键": "데스크톱 입력 단축키", "全局快捷键": "전역 단축키", "启用全局快捷键": "전역 단축키 사용", "确认 / 下一步": "확인 / 다음", "上一个选项": "이전 옵션", "下一个选项": "다음 옵션", "还原默认": "기본값 복원", "作者GitHub主页": "작성자 GitHub", "作者B站主页": "작성자 Bilibili", "打开GitHub": "GitHub 열기", "打开B站": "Bilibili 열기", "打开GitHub Issues": "GitHub Issues 열기"
  },
  de: {
    "语言包管理": "Sprachpakete", "管理语言包": "Sprachen verwalten", "退出后是否保持页面": "Ansicht nach dem Schließen behalten", "不保持": "Nicht behalten", "保持当前筛选": "Aktuelle Filter behalten", "保持当月界面": "Aktuelle Monatsansicht behalten",
    "删除后将从语言选项中隐藏，可随时恢复。简体中文为内置基础语言。": "Eine entfernte Sprache wird ausgeblendet und kann jederzeit wiederhergestellt werden. Vereinfachtes Chinesisch ist integriert.", "删除的语言包会从语言列表隐藏，之后仍可在这里恢复。": "Entfernte Sprachen werden ausgeblendet und können hier wiederhergestellt werden.", "内置基础语言": "Integrierte Basissprache", "已安装": "Installiert", "已删除": "Entfernt", "内置": "Integriert", "恢复": "Wiederherstellen", "管理": "Verwalten",
    "返回顶部按钮": "Nach-oben-Schaltfläche", "收入颜色": "Farbe für Einnahmen", "支出颜色": "Farbe für Ausgaben",
    "打开赞助面板": "Unterstützung öffnen", "打开反馈面板": "Feedback öffnen", "录入方式": "Erfassungsmodus", "记账方式": "Erfassungsoberfläche", "桌面版为全程键盘记账；手机版为完整表单记账。": "Desktop ermöglicht eine reine Tastatureingabe; mobil wird ein vollständiges Formular verwendet.", "手机版连续记账": "Fortlaufende mobile Erfassung", "手机版保存后打开仪表盘": "Nach mobiler Speicherung Dashboard öffnen", "允许内容重复": "Doppelte Beschreibungen erlauben", "关闭后，新建或修改账目时不允许与同日账目使用相同内容。": "Wenn deaktiviert, dürfen Buchungen desselben Tages keine identische Beschreibung haben.",
    "录入字段与顺序": "Eingabefelder und Reihenfolge", "录入预设": "Eingabevorgaben", "明细行为": "Tabellenverhalten", "恢复默认列宽": "Standardspaltenbreiten wiederherstellen", "启用行内编辑": "Inline-Bearbeitung aktivieren", "删除前二次确认": "Vor dem Löschen bestätigen", "撤销删除时间": "Zeit zum Rückgängigmachen", "可设置为0-15秒，只能设置为整数。": "Geben Sie eine ganze Zahl von 0 bis 15 Sekunden ein.", "显示编辑按钮": "Bearbeiten-Schaltfläche anzeigen", "显示打开Markdown按钮": "Markdown-Schaltfläche anzeigen", "显示删除按钮": "Löschen-Schaltfläche anzeigen", "表头顺序": "Spaltenreihenfolge", "拖动左侧滑块调整顺序；右侧眼睛控制是否显示，铅笔控制能否行内编辑。": "Am linken Griff sortieren; das Auge steuert die Sichtbarkeit, der Stift die Inline-Bearbeitung.",
    "金额格式": "Betragsformat", "货币符号": "Währungssymbol", "仅修改符号，不转换金额。": "Ändert nur das Symbol und rechnet Beträge nicht um.", "金额分位方式": "Zifferngruppierung", "中文万位分组（1,0000）": "Chinesische 4er-Gruppierung (1,0000)", "国际千位分组（10,000）": "Internationale 3er-Gruppierung (10,000)", "不使用分隔符（10000）": "Ohne Trennzeichen (10000)", "日期、时间与星期": "Datum, Uhrzeit und Woche", "年月格式": "Jahr-Monat-Format", "用于仪表盘的月份选择。": "Wird für die Monatsauswahl im Dashboard verwendet.", "账目日期格式": "Datumsformat der Buchungen", "用于账目明细、汇总和图表提示。": "Wird in Tabelle, Zusammenfassungen und Diagrammhinweisen verwendet.", "时间格式": "Zeitformat", "24小时制（18:30）": "24 Stunden (18:30)", "12小时制（06:30 PM）": "12 Stunden (06:30 PM)", "每周起始日": "Erster Wochentag",
    "存储目录": "Speicherordner", "账目存储目录": "Buchungsordner", "CSV导出目录": "CSV-Exportordner", "附件存储目录": "Anlagenordner", "Markdown算式存储": "Speicherung von Markdown-Formeln", "把算式写入备注": "Formeln in Notizen schreiben", "桌面版记账快捷键": "Tastenkürzel für Desktop-Erfassung", "全局快捷键": "Globale Tastenkürzel", "启用全局快捷键": "Globale Tastenkürzel aktivieren", "确认 / 下一步": "Bestätigen / Weiter", "上一个选项": "Vorherige Option", "下一个选项": "Nächste Option", "还原默认": "Standard wiederherstellen", "作者GitHub主页": "GitHub des Autors", "作者B站主页": "Bilibili des Autors", "打开GitHub": "GitHub öffnen", "打开B站": "Bilibili öffnen", "打开GitHub Issues": "GitHub Issues öffnen"
  },
  pt: {
    "语言包管理": "Pacotes de idioma", "管理语言包": "Gerir idiomas", "退出后是否保持页面": "Manter a página ao fechar", "不保持": "Não manter", "保持当前筛选": "Manter filtros atuais", "保持当月界面": "Manter a vista do mês atual",
    "删除后将从语言选项中隐藏，可随时恢复。简体中文为内置基础语言。": "Um idioma removido fica oculto e pode ser restaurado a qualquer momento. O chinês simplificado está integrado.", "删除的语言包会从语言列表隐藏，之后仍可在这里恢复。": "Os idiomas removidos ficam ocultos e podem ser restaurados aqui.", "内置基础语言": "Idioma base integrado", "已安装": "Instalado", "已删除": "Removido", "内置": "Integrado", "恢复": "Restaurar", "管理": "Gerir",
    "返回顶部按钮": "Botão voltar ao topo", "收入颜色": "Cor das receitas", "支出颜色": "Cor das despesas",
    "打开赞助面板": "Abrir apoio", "打开反馈面板": "Abrir comentários", "录入方式": "Modo de registo", "记账方式": "Interface de registo", "桌面版为全程键盘记账；手机版为完整表单记账。": "No computador, o registo pode ser feito apenas com o teclado; no telemóvel usa um formulário completo.", "手机版连续记账": "Registo contínuo no telemóvel", "手机版保存后打开仪表盘": "Abrir painel após guardar no telemóvel", "允许内容重复": "Permitir descrições repetidas", "关闭后，新建或修改账目时不允许与同日账目使用相同内容。": "Quando desativado, transações do mesmo dia não podem ter a mesma descrição.",
    "录入字段与顺序": "Campos de registo e ordem", "录入预设": "Predefinições de registo", "明细行为": "Comportamento da tabela", "恢复默认列宽": "Restaurar larguras predefinidas", "启用行内编辑": "Ativar edição na linha", "删除前二次确认": "Confirmar antes de eliminar", "撤销删除时间": "Tempo para anular eliminação", "可设置为0-15秒，只能设置为整数。": "Introduza um inteiro de 0 a 15 segundos.", "显示编辑按钮": "Mostrar botão Editar", "显示打开Markdown按钮": "Mostrar botão Markdown", "显示删除按钮": "Mostrar botão Eliminar", "表头顺序": "Ordem das colunas", "拖动左侧滑块调整顺序；右侧眼睛控制是否显示，铅笔控制能否行内编辑。": "Arraste a pega esquerda; o olho controla a visibilidade e o lápis a edição na linha.",
    "金额格式": "Formato dos valores", "货币符号": "Símbolo monetário", "仅修改符号，不转换金额。": "Altera apenas o símbolo, sem converter valores.", "金额分位方式": "Agrupamento de algarismos", "中文万位分组（1,0000）": "Agrupamento chinês de 4 algarismos (1,0000)", "国际千位分组（10,000）": "Agrupamento internacional de 3 algarismos (10,000)", "不使用分隔符（10000）": "Sem separador (10000)", "日期、时间与星期": "Data, hora e semana", "年月格式": "Formato ano-mês", "用于仪表盘的月份选择。": "Usado no seletor de mês do painel.", "账目日期格式": "Formato da data das transações", "用于账目明细、汇总和图表提示。": "Usado na tabela, nos resumos e nas dicas dos gráficos.", "时间格式": "Formato da hora", "24小时制（18:30）": "24 horas (18:30)", "12小时制（06:30 PM）": "12 horas (06:30 PM)", "每周起始日": "Primeiro dia da semana",
    "存储目录": "Pastas de armazenamento", "账目存储目录": "Pasta das transações", "CSV导出目录": "Pasta de exportação CSV", "附件存储目录": "Pasta dos anexos", "Markdown算式存储": "Armazenamento de fórmulas Markdown", "把算式写入备注": "Escrever fórmulas nas notas", "桌面版记账快捷键": "Atalhos de registo no computador", "全局快捷键": "Atalhos globais", "启用全局快捷键": "Ativar atalhos globais", "确认 / 下一步": "Confirmar / Seguinte", "上一个选项": "Opção anterior", "下一个选项": "Opção seguinte", "还原默认": "Restaurar predefinições", "作者GitHub主页": "GitHub do autor", "作者B站主页": "Página Bilibili do autor", "打开GitHub": "Abrir GitHub", "打开B站": "Abrir Bilibili", "打开GitHub Issues": "Abrir GitHub Issues"
  },
  fa: {
    "语言包管理": "بسته‌های زبان", "管理语言包": "مدیریت زبان‌ها", "退出后是否保持页面": "نگه‌داشتن صفحه پس از بستن", "不保持": "نگه‌داری نشود", "保持当前筛选": "فیلترهای فعلی حفظ شوند", "保持当月界面": "نمای ماه فعلی حفظ شود",
    "删除后将从语言选项中隐藏，可随时恢复。简体中文为内置基础语言。": "زبان حذف‌شده از فهرست پنهان می‌شود و هر زمان قابل بازیابی است. چینی ساده به‌صورت داخلی وجود دارد.", "删除的语言包会从语言列表隐藏，之后仍可在这里恢复。": "زبان‌های حذف‌شده پنهان می‌شوند و از اینجا قابل بازیابی هستند.", "内置基础语言": "زبان پایه داخلی", "已安装": "نصب‌شده", "已删除": "حذف‌شده", "内置": "داخلی", "恢复": "بازیابی", "管理": "مدیریت",
    "返回顶部按钮": "دکمه بازگشت به بالا", "收入颜色": "رنگ درآمد", "支出颜色": "رنگ هزینه",
    "打开赞助面板": "بازکردن صفحه حمایت", "打开反馈面板": "بازکردن بازخورد", "录入方式": "روش ثبت", "记账方式": "رابط ثبت", "桌面版为全程键盘记账；手机版为完整表单记账。": "نسخه رومیزی ثبت کاملاً صفحه‌کلیدی دارد و نسخه موبایل از فرم کامل استفاده می‌کند.", "手机版连续记账": "ثبت پیوسته موبایل", "手机版保存后打开仪表盘": "بازکردن داشبورد پس از ذخیره در موبایل", "允许内容重复": "اجازه شرح تکراری", "关闭后，新建或修改账目时不允许与同日账目使用相同内容。": "در صورت غیرفعال بودن، تراکنش‌های یک روز نمی‌توانند شرح یکسان داشته باشند.",
    "录入字段与顺序": "فیلدهای ثبت و ترتیب", "录入预设": "پیش‌تنظیم‌های ثبت", "明细行为": "رفتار جدول", "恢复默认列宽": "بازیابی عرض پیش‌فرض ستون‌ها", "启用行内编辑": "فعال‌سازی ویرایش درون‌ردیفی", "删除前二次确认": "تأیید پیش از حذف", "撤销删除时间": "زمان بازگردانی حذف", "可设置为0-15秒，只能设置为整数。": "عدد صحیحی از ۰ تا ۱۵ ثانیه وارد کنید.", "显示编辑按钮": "نمایش دکمه ویرایش", "显示打开Markdown按钮": "نمایش دکمه Markdown", "显示删除按钮": "نمایش دکمه حذف", "表头顺序": "ترتیب ستون‌ها", "拖动左侧滑块调整顺序；右侧眼睛控制是否显示，铅笔控制能否行内编辑。": "دستگیره چپ را بکشید؛ چشم نمایش و مداد ویرایش درون‌ردیفی را کنترل می‌کند.",
    "金额格式": "قالب مبلغ", "货币符号": "نماد ارز", "仅修改符号，不转换金额。": "فقط نماد را تغییر می‌دهد و مبلغ را تبدیل نمی‌کند.", "金额分位方式": "گروه‌بندی ارقام", "中文万位分组（1,0000）": "گروه‌بندی چینی چهارتایی (1,0000)", "国际千位分组（10,000）": "گروه‌بندی بین‌المللی سه‌تایی (10,000)", "不使用分隔符（10000）": "بدون جداکننده (10000)", "日期、时间与星期": "تاریخ، زمان و هفته", "年月格式": "قالب سال و ماه", "用于仪表盘的月份选择。": "برای انتخاب ماه داشبورد استفاده می‌شود.", "账目日期格式": "قالب تاریخ تراکنش", "用于账目明细、汇总和图表提示。": "در جدول، خلاصه‌ها و راهنمای نمودارها استفاده می‌شود.", "时间格式": "قالب زمان", "24小时制（18:30）": "۲۴ ساعته (18:30)", "12小时制（06:30 PM）": "۱۲ ساعته (06:30 PM)", "每周起始日": "نخستین روز هفته",
    "存储目录": "پوشه‌های ذخیره", "账目存储目录": "پوشه تراکنش‌ها", "CSV导出目录": "پوشه خروجی CSV", "附件存储目录": "پوشه پیوست‌ها", "Markdown算式存储": "ذخیره فرمول‌های Markdown", "把算式写入备注": "نوشتن فرمول‌ها در یادداشت", "桌面版记账快捷键": "میانبرهای ثبت رومیزی", "全局快捷键": "میانبرهای سراسری", "启用全局快捷键": "فعال‌سازی میانبرهای سراسری", "确认 / 下一步": "تأیید / بعدی", "上一个选项": "گزینه قبلی", "下一个选项": "گزینه بعدی", "还原默认": "بازیابی پیش‌فرض", "作者GitHub主页": "GitHub نویسنده", "作者B站主页": "صفحه Bilibili نویسنده", "打开GitHub": "بازکردن GitHub", "打开B站": "بازکردن Bilibili", "打开GitHub Issues": "بازکردن GitHub Issues"
  }
};

const WEEKDAY_TRANSLATIONS: Partial<Record<Language, Record<string, string>>> = {
  fr: { "周日": "Dimanche", "周一": "Lundi", "周二": "Mardi", "周三": "Mercredi", "周四": "Jeudi", "周五": "Vendredi", "周六": "Samedi", "返回上一步": "Retour", "关闭": "Fermer", "刷新仪表盘": "Actualiser le tableau de bord" },
  ru: { "周日": "Воскресенье", "周一": "Понедельник", "周二": "Вторник", "周三": "Среда", "周四": "Четверг", "周五": "Пятница", "周六": "Суббота", "返回上一步": "Назад", "关闭": "Закрыть", "刷新仪表盘": "Обновить панель" },
  es: { "周日": "Domingo", "周一": "Lunes", "周二": "Martes", "周三": "Miércoles", "周四": "Jueves", "周五": "Viernes", "周六": "Sábado", "返回上一步": "Volver", "关闭": "Cerrar", "刷新仪表盘": "Actualizar el panel" },
  ar: { "周日": "الأحد", "周一": "الاثنين", "周二": "الثلاثاء", "周三": "الأربعاء", "周四": "الخميس", "周五": "الجمعة", "周六": "السبت", "返回上一步": "رجوع", "关闭": "إغلاق", "刷新仪表盘": "تحديث لوحة المعلومات" },
  ja: { "周日": "日曜日", "周一": "月曜日", "周二": "火曜日", "周三": "水曜日", "周四": "木曜日", "周五": "金曜日", "周六": "土曜日", "返回上一步": "戻る", "关闭": "閉じる", "刷新仪表盘": "ダッシュボードを更新" },
  ko: { "周日": "일요일", "周一": "월요일", "周二": "화요일", "周三": "수요일", "周四": "목요일", "周五": "금요일", "周六": "토요일", "返回上一步": "뒤로", "关闭": "닫기", "刷新仪表盘": "대시보드 새로고침" },
  de: { "周日": "Sonntag", "周一": "Montag", "周二": "Dienstag", "周三": "Mittwoch", "周四": "Donnerstag", "周五": "Freitag", "周六": "Samstag", "返回上一步": "Zurück", "关闭": "Schließen", "刷新仪表盘": "Dashboard aktualisieren" },
  pt: { "周日": "Domingo", "周一": "Segunda-feira", "周二": "Terça-feira", "周三": "Quarta-feira", "周四": "Quinta-feira", "周五": "Sexta-feira", "周六": "Sábado", "返回上一步": "Voltar", "关闭": "Fechar", "刷新仪表盘": "Atualizar painel" },
  fa: { "周日": "یکشنبه", "周一": "دوشنبه", "周二": "سه‌شنبه", "周三": "چهارشنبه", "周四": "پنجشنبه", "周五": "جمعه", "周六": "شنبه", "返回上一步": "بازگشت", "关闭": "بستن", "刷新仪表盘": "تازه‌سازی داشبورد" }
};

for (const [language, values] of Object.entries(WEEKDAY_TRANSLATIONS) as Array<[Language, Record<string, string>]>) {
  const target = SETTINGS_TRANSLATIONS[language] ?? {};
  SETTINGS_TRANSLATIONS[language] = target;
  Object.assign(target, values);
}

interface PresetVocabulary {
  restoredWidths: string;
  invalidUndo: string;
  second: string;
  headerName: string;
  showEdit: string;
  openDashboard: string;
  drag: string;
  enable: string;
  toggleVisible: string;
  toggleEditable: string;
  capture: string;
  capturing: string;
  unset: string;
  restoreShortcuts: string;
  categoryPanel: string;
  expenseCategory: string;
  incomeCategory: string;
  name: string;
  code: string;
  effect: string;
  done: string;
  defaultValue: string;
  type: string;
  necessity: string;
  category: string;
  account: string;
  duplicate: string;
  empty: string;
  remove: string;
  newValue: string;
  nameCodeEmpty: string;
  nameOrCodeDuplicate: string;
  positive: string;
  negative: string;
  neutral: string;
  entryCode: string;
  codeEmpty: string;
  codeDuplicate: string;
}

const PRESET_VOCABULARY: Partial<Record<Language, PresetVocabulary>> = {
  fr: { restoredWidths: "Largeurs automatiques restaurées", invalidUndo: "Le délai d’annulation doit être un entier de 0 à 15 secondes", second: "s", headerName: "Nom de colonne", showEdit: "Afficher / Modifier", openDashboard: "Ouvrir le tableau de bord", drag: "Faire glisser pour trier", enable: "Activer", toggleVisible: "Basculer l’affichage de la colonne", toggleEditable: "Basculer la modification en ligne", capture: "Cliquez puis appuyez sur le raccourci", capturing: "Appuyez sur un raccourci…", unset: "Remettre à non défini", restoreShortcuts: "Rétablir les raccourcis", categoryPanel: "Section de catégories", expenseCategory: "Catégories de dépenses", incomeCategory: "Catégories de revenus", name: "Nom", code: "Code", effect: "Traitement", done: "Terminer", defaultValue: "Valeur par défaut", type: "type", necessity: "nécessité", category: "catégorie", account: "compte", duplicate: "Le nom {value} doit être unique", empty: "Le nom {value} ne peut pas être vide", remove: "Supprimer {value}", newValue: "Nouveau nom de {value}", nameCodeEmpty: "Le nom et le code sont obligatoires", nameOrCodeDuplicate: "Le nom ou le code de {value} doit être unique", positive: "+revenu", negative: "−dépense", neutral: "Ne pas comptabiliser", entryCode: "Code de saisie", codeEmpty: "Le code ne peut pas être vide", codeDuplicate: "Les codes d’un même groupe doivent être uniques" },
  ru: { restoredWidths: "Автоматическая ширина столбцов восстановлена", invalidUndo: "Время отмены должно быть целым числом от 0 до 15 секунд", second: "с", headerName: "Название столбца", showEdit: "Показать / Изменить", openDashboard: "Открыть панель", drag: "Перетащить для сортировки", enable: "Включить", toggleVisible: "Переключить видимость столбца", toggleEditable: "Переключить редактирование в строке", capture: "Нажмите здесь, затем клавиши", capturing: "Нажмите сочетание…", unset: "Сбросить", restoreShortcuts: "Восстановить горячие клавиши", categoryPanel: "Раздел категорий", expenseCategory: "Категории расходов", incomeCategory: "Категории доходов", name: "Название", code: "Код", effect: "Учёт", done: "Готово", defaultValue: "Значение по умолчанию", type: "типа", necessity: "необходимости", category: "категории", account: "счёта", duplicate: "Название {value} должно быть уникальным", empty: "Название {value} не может быть пустым", remove: "Удалить {value}", newValue: "Новое название {value}", nameCodeEmpty: "Название и код обязательны", nameOrCodeDuplicate: "Название или код {value} должны быть уникальными", positive: "+доход", negative: "−расход", neutral: "Не учитывать", entryCode: "Код ввода", codeEmpty: "Код не может быть пустым", codeDuplicate: "Коды в одной группе должны быть уникальными" },
  es: { restoredWidths: "Se restauraron los anchos automáticos", invalidUndo: "El tiempo para deshacer debe ser un entero de 0 a 15 segundos", second: "s", headerName: "Nombre de columna", showEdit: "Mostrar / Editar", openDashboard: "Abrir el panel", drag: "Arrastrar para ordenar", enable: "Activar", toggleVisible: "Cambiar visibilidad de columna", toggleEditable: "Cambiar edición en línea", capture: "Haz clic y pulsa el atajo", capturing: "Pulsa un atajo…", unset: "Dejar sin asignar", restoreShortcuts: "Restaurar atajos", categoryPanel: "Sección de categorías", expenseCategory: "Categorías de gastos", incomeCategory: "Categorías de ingresos", name: "Nombre", code: "Código", effect: "Tratamiento", done: "Listo", defaultValue: "Valor predeterminado", type: "tipo", necessity: "necesidad", category: "categoría", account: "cuenta", duplicate: "El nombre de {value} debe ser único", empty: "El nombre de {value} no puede estar vacío", remove: "Eliminar {value}", newValue: "Nuevo nombre de {value}", nameCodeEmpty: "El nombre y el código son obligatorios", nameOrCodeDuplicate: "El nombre o código de {value} debe ser único", positive: "+ingreso", negative: "−gasto", neutral: "No contabilizar", entryCode: "Código de registro", codeEmpty: "El código no puede estar vacío", codeDuplicate: "Los códigos de un mismo grupo deben ser únicos" },
  ar: { restoredWidths: "تمت استعادة عرض الأعمدة التلقائي", invalidUndo: "يجب أن تكون مدة التراجع عدداً صحيحاً من 0 إلى 15 ثانية", second: "ث", headerName: "اسم العمود", showEdit: "عرض / تعديل", openDashboard: "فتح لوحة المعلومات", drag: "اسحب للترتيب", enable: "تمكين", toggleVisible: "تبديل ظهور العمود", toggleEditable: "تبديل التحرير داخل الصف", capture: "انقر ثم اضغط الاختصار", capturing: "اضغط اختصاراً…", unset: "إلغاء التعيين", restoreShortcuts: "استعادة الاختصارات", categoryPanel: "قسم الفئات", expenseCategory: "فئات المصروفات", incomeCategory: "فئات الدخل", name: "الاسم", code: "الرمز", effect: "طريقة الاحتساب", done: "تم", defaultValue: "القيمة الافتراضية", type: "النوع", necessity: "الضرورة", category: "الفئة", account: "الحساب", duplicate: "يجب ألا يتكرر اسم {value}", empty: "لا يمكن أن يكون اسم {value} فارغاً", remove: "حذف {value}", newValue: "اسم {value} جديد", nameCodeEmpty: "الاسم والرمز مطلوبان", nameOrCodeDuplicate: "يجب ألا يتكرر اسم {value} أو رمزه", positive: "+دخل", negative: "−مصروف", neutral: "لا يُحتسب", entryCode: "رمز الإدخال", codeEmpty: "لا يمكن أن يكون الرمز فارغاً", codeDuplicate: "يجب ألا تتكرر الرموز ضمن المجموعة نفسها" },
  ja: { restoredWidths: "自動列幅を復元しました", invalidUndo: "取り消し時間は0～15秒の整数にしてください", second: "秒", headerName: "列名", showEdit: "表示 / 編集", openDashboard: "ダッシュボードを開く", drag: "ドラッグして並べ替え", enable: "有効", toggleVisible: "列の表示を切り替え", toggleEditable: "行内編集を切り替え", capture: "クリックしてショートカットを押す", capturing: "ショートカットを押してください…", unset: "未設定に戻す", restoreShortcuts: "ショートカットを既定に戻す", categoryPanel: "カテゴリ区分", expenseCategory: "支出カテゴリ", incomeCategory: "収入カテゴリ", name: "名前", code: "コード", effect: "計上方法", done: "完了", defaultValue: "既定の入力値", type: "種類", necessity: "必要性", category: "カテゴリ", account: "口座", duplicate: "{value}名は重複できません", empty: "{value}名は空にできません", remove: "{value}を削除", newValue: "新しい{value}名", nameCodeEmpty: "名前とコードは必須です", nameOrCodeDuplicate: "{value}名またはコードは重複できません", positive: "+収入", negative: "−支出", neutral: "計上しない", entryCode: "入力コード", codeEmpty: "コードは空にできません", codeDuplicate: "同じグループのコードは重複できません" },
  ko: { restoredWidths: "자동 열 너비를 복원했습니다", invalidUndo: "삭제 취소 시간은 0~15초의 정수여야 합니다", second: "초", headerName: "열 이름", showEdit: "표시 / 편집", openDashboard: "대시보드 열기", drag: "드래그하여 정렬", enable: "사용", toggleVisible: "열 표시 전환", toggleEditable: "행 편집 전환", capture: "클릭한 뒤 단축키를 누르세요", capturing: "단축키를 누르세요…", unset: "미설정으로 복원", restoreShortcuts: "기본 단축키 복원", categoryPanel: "분류 구역", expenseCategory: "지출 분류", incomeCategory: "수입 분류", name: "이름", code: "코드", effect: "반영 방식", done: "완료", defaultValue: "기본 입력값", type: "유형", necessity: "필요성", category: "분류", account: "계정", duplicate: "{value} 이름은 중복될 수 없습니다", empty: "{value} 이름은 비워 둘 수 없습니다", remove: "{value} 삭제", newValue: "새 {value} 이름", nameCodeEmpty: "이름과 코드는 필수입니다", nameOrCodeDuplicate: "{value} 이름 또는 코드는 중복될 수 없습니다", positive: "+수입", negative: "−지출", neutral: "반영 안 함", entryCode: "입력 코드", codeEmpty: "코드는 비워 둘 수 없습니다", codeDuplicate: "같은 그룹의 코드는 중복될 수 없습니다" },
  de: { restoredWidths: "Automatische Spaltenbreiten wiederhergestellt", invalidUndo: "Die Rückgängig-Zeit muss eine ganze Zahl von 0 bis 15 Sekunden sein", second: "s", headerName: "Spaltenname", showEdit: "Anzeigen / Bearbeiten", openDashboard: "Dashboard öffnen", drag: "Zum Sortieren ziehen", enable: "Aktivieren", toggleVisible: "Spaltensichtbarkeit umschalten", toggleEditable: "Inline-Bearbeitung umschalten", capture: "Klicken und Tastenkürzel drücken", capturing: "Tastenkürzel drücken…", unset: "Auf nicht festgelegt setzen", restoreShortcuts: "Standardkürzel wiederherstellen", categoryPanel: "Kategoriebereich", expenseCategory: "Ausgabenkategorien", incomeCategory: "Einnahmekategorien", name: "Name", code: "Code", effect: "Berücksichtigung", done: "Fertig", defaultValue: "Standardwert", type: "Typ", necessity: "Notwendigkeit", category: "Kategorie", account: "Konto", duplicate: "Der Name für {value} muss eindeutig sein", empty: "Der Name für {value} darf nicht leer sein", remove: "{value} löschen", newValue: "Neuer Name für {value}", nameCodeEmpty: "Name und Code sind erforderlich", nameOrCodeDuplicate: "Name oder Code für {value} muss eindeutig sein", positive: "+Einnahme", negative: "−Ausgabe", neutral: "Nicht berücksichtigen", entryCode: "Eingabecode", codeEmpty: "Der Code darf nicht leer sein", codeDuplicate: "Codes derselben Gruppe müssen eindeutig sein" },
  pt: { restoredWidths: "Larguras automáticas restauradas", invalidUndo: "O tempo para anular deve ser um inteiro de 0 a 15 segundos", second: "s", headerName: "Nome da coluna", showEdit: "Mostrar / Editar", openDashboard: "Abrir painel", drag: "Arrastar para ordenar", enable: "Ativar", toggleVisible: "Alternar visibilidade da coluna", toggleEditable: "Alternar edição na linha", capture: "Clique e prima o atalho", capturing: "Prima um atalho…", unset: "Voltar a não definido", restoreShortcuts: "Restaurar atalhos", categoryPanel: "Secção de categorias", expenseCategory: "Categorias de despesas", incomeCategory: "Categorias de receitas", name: "Nome", code: "Código", effect: "Tratamento", done: "Concluído", defaultValue: "Valor predefinido", type: "tipo", necessity: "necessidade", category: "categoria", account: "conta", duplicate: "O nome de {value} deve ser único", empty: "O nome de {value} não pode estar vazio", remove: "Eliminar {value}", newValue: "Novo nome de {value}", nameCodeEmpty: "O nome e o código são obrigatórios", nameOrCodeDuplicate: "O nome ou código de {value} deve ser único", positive: "+receita", negative: "−despesa", neutral: "Não contabilizar", entryCode: "Código de registo", codeEmpty: "O código não pode estar vazio", codeDuplicate: "Os códigos do mesmo grupo devem ser únicos" },
  fa: { restoredWidths: "عرض خودکار ستون‌ها بازیابی شد", invalidUndo: "زمان بازگردانی باید عدد صحیحی از ۰ تا ۱۵ ثانیه باشد", second: "ث", headerName: "نام ستون", showEdit: "نمایش / ویرایش", openDashboard: "بازکردن داشبورد", drag: "برای مرتب‌سازی بکشید", enable: "فعال‌سازی", toggleVisible: "تغییر نمایش ستون", toggleEditable: "تغییر ویرایش درون‌ردیفی", capture: "کلیک کنید و میانبر را بزنید", capturing: "میانبر را فشار دهید…", unset: "بازگردانی به تنظیم‌نشده", restoreShortcuts: "بازیابی میانبرها", categoryPanel: "بخش دسته‌ها", expenseCategory: "دسته‌های هزینه", incomeCategory: "دسته‌های درآمد", name: "نام", code: "کد", effect: "روش محاسبه", done: "انجام شد", defaultValue: "مقدار پیش‌فرض", type: "نوع", necessity: "ضرورت", category: "دسته", account: "حساب", duplicate: "نام {value} نباید تکراری باشد", empty: "نام {value} نمی‌تواند خالی باشد", remove: "حذف {value}", newValue: "نام جدید {value}", nameCodeEmpty: "نام و کد الزامی هستند", nameOrCodeDuplicate: "نام یا کد {value} نباید تکراری باشد", positive: "+درآمد", negative: "−هزینه", neutral: "محاسبه نشود", entryCode: "کد ثبت", codeEmpty: "کد نمی‌تواند خالی باشد", codeDuplicate: "کدهای یک گروه نباید تکراری باشند" }
};

function fill(template: string, value: string): string {
  return template.replace("{value}", value);
}

for (const [language, words] of Object.entries(PRESET_VOCABULARY) as Array<[Language, PresetVocabulary]>) {
  const target = SETTINGS_TRANSLATIONS[language] ?? {};
  SETTINGS_TRANSLATIONS[language] = target;
  const groups = { "类型": words.type, "必要性": words.necessity, "分类": words.category, "账户": words.account };
  Object.assign(target, {
    "已恢复账目明细自动列宽": words.restoredWidths, "撤销删除时间必须是0—15秒的整数": words.invalidUndo, "秒": words.second, "表头名称": words.headerName, "显示 / 编辑": words.showEdit, "打开仪表盘": words.openDashboard, "拖动排序": words.drag, "启用": words.enable, "切换表头显示": words.toggleVisible, "切换行内编辑": words.toggleEditable, "点击后按下快捷键": words.capture, "请按下快捷键…": words.capturing, "还原为未设置": words.unset, "还原默认快捷键": words.restoreShortcuts, "分类板块": words.categoryPanel, "支出分类": words.expenseCategory, "收入分类": words.incomeCategory, "名称": words.name, "编号": words.code, "计入方式": words.effect, "完成": words.done, "默认录入值": words.defaultValue, "+收入": words.positive, "−支出": words.negative, "不计入": words.neutral, "录入编号": words.entryCode, "编号不能为空": words.codeEmpty, "同一组选项的编号不能重复": words.codeDuplicate, "名称和编号不能为空": words.nameCodeEmpty
  });
  for (const [source, value] of Object.entries(groups)) {
    target[`${source}名称`] = `${words.name}: ${value}`;
    target[`${source}名称不能重复`] = fill(words.duplicate, value);
    target[`${source}名称不能为空`] = fill(words.empty, value);
    target[`删除${source}`] = fill(words.remove, value);
    target[`新${source}名称`] = fill(words.newValue, value);
    target[`${source}名称或编号不能重复`] = fill(words.nameOrCodeDuplicate, value);
  }
}

const META_TRANSLATIONS: Partial<Record<Language, Record<string, string>>> = {
  fr: { "打开Easy Bookkeeping GitHub主页": "Ouvrir la page GitHub d’Easy Bookkeeping", "作者：北漠海": "Auteur : Beimohai", "更新日期：2026-08-07": "Date de mise à jour : 2026-08-07", "本项目基于 MIT License 开源": "Ce projet est open source sous licence MIT", "微信与支付宝收款码": "Codes de paiement WeChat Pay et Alipay", "QQ群588526922二维码": "Code QR du groupe QQ 588526922" },
  ru: { "打开Easy Bookkeeping GitHub主页": "Открыть GitHub Easy Bookkeeping", "作者：北漠海": "Автор: Beimohai", "更新日期：2026-08-07": "Дата обновления: 2026-08-07", "本项目基于 MIT License 开源": "Проект распространяется с открытым исходным кодом по лицензии MIT", "微信与支付宝收款码": "Платёжные QR-коды WeChat Pay и Alipay", "QQ群588526922二维码": "QR-код группы QQ 588526922" },
  es: { "打开Easy Bookkeeping GitHub主页": "Abrir GitHub de Easy Bookkeeping", "作者：北漠海": "Autor: Beimohai", "更新日期：2026-08-07": "Fecha de actualización: 2026-08-07", "本项目基于 MIT License 开源": "Este proyecto es de código abierto con licencia MIT", "微信与支付宝收款码": "Códigos de pago WeChat Pay y Alipay", "QQ群588526922二维码": "Código QR del grupo QQ 588526922" },
  ar: { "打开Easy Bookkeeping GitHub主页": "فتح GitHub الخاص بـ Easy Bookkeeping", "作者：北漠海": "المؤلف: Beimohai", "更新日期：2026-08-07": "تاريخ التحديث: 2026-08-07", "本项目基于 MIT License 开源": "هذا المشروع مفتوح المصدر بموجب ترخيص MIT", "微信与支付宝收款码": "رموز دفع WeChat Pay وAlipay", "QQ群588526922二维码": "رمز QR لمجموعة QQ 588526922" },
  ja: { "打开Easy Bookkeeping GitHub主页": "Easy Bookkeeping のGitHubを開く", "作者：北漠海": "作者：Beimohai", "更新日期：2026-08-07": "更新日：2026-08-07", "本项目基于 MIT License 开源": "本プロジェクトはMITライセンスで公開されています", "微信与支付宝收款码": "WeChat Pay・Alipay 支払いコード", "QQ群588526922二维码": "QQグループ588526922のQRコード" },
  ko: { "打开Easy Bookkeeping GitHub主页": "Easy Bookkeeping GitHub 열기", "作者：北漠海": "작성자: Beimohai", "更新日期：2026-08-07": "업데이트 날짜: 2026-08-07", "本项目基于 MIT License 开源": "이 프로젝트는 MIT 라이선스로 공개됩니다", "微信与支付宝收款码": "WeChat Pay 및 Alipay 결제 코드", "QQ群588526922二维码": "QQ 그룹 588526922 QR 코드" },
  de: { "打开Easy Bookkeeping GitHub主页": "Easy-Bookkeeping-GitHub öffnen", "作者：北漠海": "Autor: Beimohai", "更新日期：2026-08-07": "Aktualisiert: 2026-08-07", "本项目基于 MIT License 开源": "Dieses Projekt ist unter der MIT-Lizenz quelloffen", "微信与支付宝收款码": "Zahlungscodes für WeChat Pay und Alipay", "QQ群588526922二维码": "QR-Code der QQ-Gruppe 588526922" },
  pt: { "打开Easy Bookkeeping GitHub主页": "Abrir GitHub do Easy Bookkeeping", "作者：北漠海": "Autor: Beimohai", "更新日期：2026-08-07": "Data da atualização: 2026-08-07", "本项目基于 MIT License 开源": "Este projeto é de código aberto sob a licença MIT", "微信与支付宝收款码": "Códigos de pagamento WeChat Pay e Alipay", "QQ群588526922二维码": "Código QR do grupo QQ 588526922" },
  fa: { "打开Easy Bookkeeping GitHub主页": "بازکردن GitHub نرم‌افزار Easy Bookkeeping", "作者：北漠海": "نویسنده: Beimohai", "更新日期：2026-08-07": "تاریخ به‌روزرسانی: 2026-08-07", "本项目基于 MIT License 开源": "این پروژه با مجوز MIT متن‌باز است", "微信与支付宝收款码": "کدهای پرداخت WeChat Pay وAlipay", "QQ群588526922二维码": "کد QR گروه QQ 588526922" }
};

for (const [language, values] of Object.entries(META_TRANSLATIONS) as Array<[Language, Record<string, string>]>) {
  const target = SETTINGS_TRANSLATIONS[language] ?? {};
  SETTINGS_TRANSLATIONS[language] = target;
  Object.assign(target, values);
}

const SCROLLBAR_TRANSLATIONS: Partial<Record<Language, [string, string]>> = {
  fr: ["Barre de défilement horizontale supérieure des opérations", "Barre de défilement horizontale inférieure des opérations"],
  ru: ["Верхняя горизонтальная полоса прокрутки операций", "Нижняя горизонтальная полоса прокрутки операций"],
  es: ["Barra de desplazamiento horizontal superior de movimientos", "Barra de desplazamiento horizontal inferior de movimientos"],
  ar: ["شريط التمرير الأفقي العلوي للمعاملات", "شريط التمرير الأفقي السفلي للمعاملات"],
  ja: ["取引明細の上側水平スクロールバー", "取引明細の下側水平スクロールバー"],
  ko: ["거래 내역 상단 가로 스크롤 막대", "거래 내역 하단 가로 스크롤 막대"],
  de: ["Obere horizontale Bildlaufleiste der Buchungen", "Untere horizontale Bildlaufleiste der Buchungen"],
  pt: ["Barra de deslocamento horizontal superior dos movimentos", "Barra de deslocamento horizontal inferior dos movimentos"],
  fa: ["نوار پیمایش افقی بالای تراکنش‌ها", "نوار پیمایش افقی پایین تراکنش‌ها"]
};

for (const [language, values] of Object.entries(SCROLLBAR_TRANSLATIONS) as Array<[Language, [string, string]]>) {
  const target = SETTINGS_TRANSLATIONS[language] ?? {};
  SETTINGS_TRANSLATIONS[language] = target;
  target["账目明细上方横向滚动条"] = values[0];
  target["账目明细下方横向滚动条"] = values[1];
}
